### ISSUE TITLE
Đăng BE - Làm chức năng thêm phản hồi

### ISSUE THREAD

**Issue by ductrannb** [bebaocute1010/TLUSurveysSystem#17]
M chỉ cần lấy nội dung phản hồi gửi về từ Request xong thêm vào database thôi. Từ Request có thể lấy cả id của người tạo khảo sát. M xem cách xử lý dữ liệu vs Request trong Laravel nha. Truyền vào Request thôi k dùng _POST hay _GET đâu.
![image](https://user-images.githubusercontent.com/82665474/222451689-c8e6f35c-7492-42bd-b007-1af4dd509c51.png)
Kiểu như thế này

**Comment by KhoaDan9** [comment]
Oke, hen anh ban dep trai vai ngay nua, dao nay toi lam viec ban qua.

**Comment by ductrannb** [comment]
vo van. Lam luon di thu 2 len roi
